#
# Copyright (C) 2025 Ashley Lee <nekokecore@emtips.net>
#
# This is free software, licensed under the GNU General Public License v2.
#

include $(TOPDIR)/rules.mk

LUCI_SECTION:=corefix
LUCI_CATEGORY:=NekokeCore Optimization
LUCI_TITLE:=NekokeCore's LuCI Base Optimization
LUCI_DEPENDS:=+luci
LUCI_PKGARCH:=all

PKG_VERSION:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
